version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout     
      - run: jupyter-nbconvert --execute ./Homework1.ipynb
      - store_artifacts:
          path: ./Homework1.html
          destination: Homework1.html 
workflows:
  main:
    jobs:
      - build
